### ISSUE TITLE
Can't create PDF using Docker image

### ISSUE THREAD

**Issue by nlamirault** [astefanutti/decktape#186] opened 2019-06-11 15:12 UTC
Hi,
i try to create a PDF using the Docker image and i've got no output file : 

```
$ lt
.rw-r--r-- nicolas users   99 B  Sun Jun  9 09:03:05 2019   README.md
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:03:05 2019   content
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:03:05 2019   conf
.rw-r--r-- nicolas users   29 KB Sun Jun  9 09:03:05 2019   asciidoctor.css
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:03:05 2019   stylesheets
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:16:25 2019   dzslides
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:44:24 2019   images
.rw-r--r-- nicolas users  926 B  Sun Jun  9 10:20:23 2019   slides.adoc
drwxr-xr-x nicolas users    4 KB Sun Jun  9 11:26:01 2019   ..
drwxr-xr-x nicolas users    4 KB Tue Jun 11 16:18:56 2019   node_modules
.rw-r--r-- nicolas users 27.1 KB Tue Jun 11 16:18:56 2019   yarn.lock
.rw-r--r-- nicolas users   53 B  Tue Jun 11 16:18:56 2019   package.json
drwxr-xr-x nicolas users    4 KB Tue Jun 11 16:47:41 2019   .
.rw-r--r-- nicolas users  1.7 KB Tue Jun 11 16:50:13 2019   Makefile
.rw-r--r-- nicolas users 78.7 KB Tue Jun 11 16:50:16 2019   slides.html

$ docker run --rm -v `pwd`:/home/user astefanutti/decktape --chrome-arg=--no-sandbox  /home/user/slides.html slides.pdf
Loading page file:///home/user/slides.html ...

Unable to load resource from URL: file:///images/noise.png
Failed to load resource: net::ERR_FILE_NOT_FOUND
Loading page finished with status: 0
DZ Slides plugin activated
Printing slide #71.0    (71/71) ...
Printed 71 slides

$ lt
.rw-r--r-- nicolas users   99 B  Sun Jun  9 09:03:05 2019   README.md
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:03:05 2019   content
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:03:05 2019   conf
.rw-r--r-- nicolas users   29 KB Sun Jun  9 09:03:05 2019   asciidoctor.css
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:03:05 2019   stylesheets
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:16:25 2019   dzslides
drwxr-xr-x nicolas users    4 KB Sun Jun  9 09:44:24 2019   images
.rw-r--r-- nicolas users  926 B  Sun Jun  9 10:20:23 2019   slides.adoc
drwxr-xr-x nicolas users    4 KB Sun Jun  9 11:26:01 2019   ..
drwxr-xr-x nicolas users    4 KB Tue Jun 11 16:18:56 2019   node_modules
.rw-r--r-- nicolas users 27.1 KB Tue Jun 11 16:18:56 2019   yarn.lock
.rw-r--r-- nicolas users   53 B  Tue Jun 11 16:18:56 2019   package.json
drwxr-xr-x nicolas users    4 KB Tue Jun 11 16:47:41 2019   .
.rw-r--r-- nicolas users  1.7 KB Tue Jun 11 16:50:13 2019   Makefile
.rw-r--r-- nicolas users 78.7 KB Tue Jun 11 16:50:16 2019   slides.html

$ docker run --rm -v `pwd`:/home/user astefanutti/decktape --chrome-arg=--no-sandbox  /home/user/slides.html /home/user/slides.pdf
TypeError: Unable to create PDF file, make sure that output file target is available
    at /decktape/decktape.js:200:26
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

```

It works fine with decktape binary : 

```
$ ./node_modules/.bin/decktape --chrome-arg=--no-sandbox slides.html slides.pdf
Loading page file:///home/nicolas/Projects/decks/kubernetes/slides.html ...

Unable to load resource from URL: file:///home/nicolas/Projects/images/noise.png
Failed to load resource: net::ERR_FILE_NOT_FOUND
Loading page finished with status: 0
DZ Slides plugin activated
Printing slide #71.0    (71/71) ...
Printed 71 slides

$ lt
lt
.rw-r--r-- nicolas users    99 B  Sun Jun  9 09:03:05 2019   README.md
drwxr-xr-x nicolas users     4 KB Sun Jun  9 09:03:05 2019   content
drwxr-xr-x nicolas users     4 KB Sun Jun  9 09:03:05 2019   conf
.rw-r--r-- nicolas users    29 KB Sun Jun  9 09:03:05 2019   asciidoctor.css
drwxr-xr-x nicolas users     4 KB Sun Jun  9 09:03:05 2019   stylesheets
drwxr-xr-x nicolas users     4 KB Sun Jun  9 09:16:25 2019   dzslides
drwxr-xr-x nicolas users     4 KB Sun Jun  9 09:44:24 2019   images
.rw-r--r-- nicolas users   926 B  Sun Jun  9 10:20:23 2019   slides.adoc
drwxr-xr-x nicolas users     4 KB Sun Jun  9 11:26:01 2019   ..
drwxr-xr-x nicolas users     4 KB Tue Jun 11 16:18:56 2019   node_modules
.rw-r--r-- nicolas users  27.1 KB Tue Jun 11 16:18:56 2019   yarn.lock
.rw-r--r-- nicolas users    53 B  Tue Jun 11 16:18:56 2019   package.json
.rw-r--r-- nicolas users   1.7 KB Tue Jun 11 16:50:13 2019   Makefile
.rw-r--r-- nicolas users  78.7 KB Tue Jun 11 16:50:16 2019   slides.html
drwxr-xr-x nicolas users     4 KB Tue Jun 11 17:07:56 2019   .
.rw-r--r-- nicolas users 861.9 KB Tue Jun 11 17:09:21 2019   slides.pdf
```

Any idea ?
Thanks.

**Comment by astefanutti** [comment] 2019-06-12 14:37
By default, the Docker image outputs the PDF in the `/slides` directory, that can be mounted with `${pwd}:/slides`. That explains why you don't see any output file.

For the second error, it seems the output folder isn't writable. You may want to try `${pwd}:/home/user:rw`. Otherwise, you may check the container can write to the mounted directory.

**Comment by astefanutti** [comment] 2019-07-03 14:04
Let speculatively close this issue. Feel free to re-open if you think it's caused by DeckTape.

**Closed by astefanutti** 2019-07-03 14:04 UTC
Labels: Docker
