### ISSUE TITLE
strong tag produces glitch on Windows 10

### ISSUE THREAD

**Issue by DanielRuf** [astefanutti/decktape#123] opened 2017-11-12 20:37 UTC
When using reveal.js and there is a strong tag in a text the rendering is weird (first letter looks a bit bold, rest doesn't

How it should look like
![bold](https://user-images.githubusercontent.com/827205/32703090-44636460-c7f1-11e7-95eb-67655ff82a4a.png)

How it actually looks like in the PDF
![image](https://user-images.githubusercontent.com/827205/32703109-690415d0-c7f1-11e7-914c-d406fe12f05b.png)

When not using the strong tag it looks like this
![image](https://user-images.githubusercontent.com/827205/32703119-929ec9da-c7f1-11e7-80be-cac366a04df2.png)

**Comment by astefanutti** [comment] 2017-11-16 18:15
I haven't been able to reproduce. Would you be able to share a minimal use case? It may be specific to the font you use.

**Comment by DanielRuf** [comment] 2017-11-16 19:15
Take a look at https://github.com/danielruf/slides

Basically I created a slide with reveal.js and used the strong tag in an unorderef list element.

**Comment by DanielRuf** [comment] 2017-11-16 19:16
The font is the one loaded by the light reveal.js theme.

**Comment by astefanutti** [comment] 2017-11-16 21:09
Still could not reproduce. Here is the result PDF: [test.pdf](https://github.com/astefanutti/decktape/files/1480248/test.pdf).

Could you indicate what DeckTape version you use, as well as your OS, the PDF viewer. If you could upload an example PDF that may help as well.

**Comment by DanielRuf** [comment] 2017-11-16 21:51
I've used Windows 10. The lockfile is committed. `npm start` will generate the pdf. I've already shutdown my pc. I can also test on my MacBook at work tomorrow. The pdf was viewed in Adobe Acrobat Reader.

**Comment by DanielRuf** [comment] 2017-11-16 22:01
[slides.pdf](https://github.com/astefanutti/decktape/files/1480395/slides.pdf)

**Comment by astefanutti** [comment] 2017-11-16 22:19
Thanks. That discards the viewer as I can see the issue using Mac OS viewer. It's unlikely to be an old DeckTape version issue as you use version 2.4.3. That would help if you could share the source of that sample so that I try reproducing.

**Comment by DanielRuf** [comment] 2017-11-16 23:38
It's a normal `<section>` with a `<ul>` and a `<li><strong>Encryption</strong><br>...</li>`.

The font files and so on are in my slides repository. The only difference is that I've added an unordered list with a list item which contains a strong.

It's a bit late now but if you need this simple example source I'll provide this as a single html file tomorrow.

Using my repo and adding a section with the aforementioned code should reproduce this.

**Comment by astefanutti** [comment] 2017-11-16 23:40
Unfortunately that's what I've tried, taking your repository and add the section to produce the sample I've attached.

**Comment by DanielRuf** [comment] 2017-11-17 06:58
I can not reproduce it on macOS 10.12. So it seems it is a Windows related issue.

**Comment by astefanutti** [comment] 2017-11-18 13:59
I've just tried on Windows 7 and still cannot reproduce: [test.pdf](https://github.com/astefanutti/decktape/files/1484626/test.pdf).

So it seems specific to Windows 10. Unfortunately I don't have a Windows 10 image readily available to troubleshoot the issue.

**Comment by mwd-sap** [comment] 2017-12-15 13:03
I have encountered the same issue, with a slideshow based on remark.

Windows 10
remark 0.14.1
decktape 2.6.1

**Comment by astefanutti** [comment] 2017-12-17 16:52
I suspect it is caused by the font compression logic that's somehow broken specifically on Windows 10. I have to find a Windows 10 box and I'll troubleshoot it ASAP.

**Comment by DanielRuf** [comment] 2017-12-17 18:43
You can use maybe the virtual machines from modern.ie.

**Comment by astefanutti** [comment] 2017-12-19 14:56
It should be fixed in version `2.6.2`.

It turns out the PDF font name does not include the font sub family on Windows 10 compared to other platforms. The font sub family is now read, among other information, from the decoded font metadata.

**Comment by astefanutti** [comment] 2017-12-19 14:57
And thanks for the report!

**Closed by astefanutti** 2017-12-19 14:56 UTC
Labels: bug

**Comment by mwd-sap** [comment] 2017-12-20 10:15
I upgraded to 2.6.3 and can confirm that this issue is resolved. Thank you!

**Comment by astefanutti** [comment] 2017-12-20 10:26
@mwd-sap thanks for the confirmation. Appreciated!
