### ISSUE TITLE
npm install presents warning about puppeteer version

### ISSUE THREAD

**Issue by DuaneOBrien** [astefanutti/decktape#198] opened 2019-10-06 22:23 UTC
`npm install` or `npm audit` raises an alert about the required version of puppeteer.

Advisory is [here](https://npmjs.com/advisories/824).

Bumping puppeteer version to 1.13 in package.json should resolve.

**Comment by astefanutti** [comment] 2019-10-07 08:24
I was holding the Puppeteer upgrade because of the following constraints: 

- The [Chromium Alpine port][1] should be available for the version used by Puppeteer
- There is a regression introduced in Chromium 75 (Puppeteer 1.15.0) that affects Mac OS PDF preview: https://crbug.com/995265

That being said, upgrading to Puppeteer 1.13.0 satisfies these two constraints and should solve the security warning. 

[1]: https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium

**Comment by astefanutti** [comment] 2019-10-07 10:02
It should be fixed with d0fcbe57701fd6f7a4ab220544a03ebcee13f98e.

Thanks a lot for the report!

**Closed by astefanutti** 2019-10-07 10:02 UTC
