### ISSUE TITLE
Mathjax rendering differs online vs offline

### ISSUE THREAD

**Issue by pat-s** [astefanutti/decktape#162] opened 2018-09-13 13:50 UTC
v2.8.8 (Arch Linux)

Correct rendering: 

`decktape --no-sandbox https://pjs-web.de/files/test/ ~/Downloads/test.pdf`

Faulty rendering: 

`decktape --no-sandbox ~/Downloads/test.html ~/Downloads/test.pdf`

Faulty preview: https://pjs-web.de/files/test.pdf

The docker image does not work due to #159.

**Comment by astefanutti** [comment] 2018-09-14 07:09
It should be fixed with fa215c47580d116ff929365c8e028f06c60594ad. I've tried it locally and it works. I'll do a release ASAP. Thanks for the report.

**Closed by astefanutti** 2018-09-14 07:09 UTC

**Comment by amotl** [comment] 2018-09-14 09:11
Hi there,

just for the records to others landing here.

The commit https://github.com/astefanutti/decktape/commit/fa215c47 referenced by @astefanutti above reverts decktape to using the **networkidle0** lifecycle event instead of **networkidle2** as a waiting condition for the central `page.goto(...)` call it issues against Puppeteer.

We originally changed the behavior (from **networkidle0** to **networkidle2**) with #150 to make page loading work with **data uri** resources. I recognize Mathjax will be more important than supporting data uris and also, the loading behavior of recent Chromium releases might have been improved in the meanwhile that this wouldn't break our specific use case.

Just wanted to leave this notice here in order to be able to revisit the issue at some time in the future where we might _make this setting configurable_ to satisfy different needs. Would you accept such an improvement to decktape, @astefanutti?

Cheers and keep up the spirit,
Andreas.

**Comment by astefanutti** [comment] 2018-09-14 09:16
Hi @amotl, thanks a lot for the heads-up.

I made this decision based on the compromise you've mentioned. In case Chromium hasn't improved and the issue is still present, I agree we can introduce a parameter that would control the loading condition that DeckTape uses.

**Comment by amotl** [comment] 2018-09-14 09:29
Thanks @astefanutti. I might come back to this after eventually updating and checking our decktape installation then.

Have a good weekend!

**Comment by pat-s** [comment] 2018-09-14 11:29
Solves the issue of the reprex but not my practical issue :disappointed: . I don't have time right now to dig deeper. Tackling it again the next time it bothers me. Maybe the problem solved itself by then. 

Thanks for solving it so quickly!
