### ISSUE TITLE
Font compression does not work for Emoji fonts

### ISSUE THREAD

**Issue by DuaneOBrien** [astefanutti/decktape#177] opened 2019-03-14 03:17 UTC
After updating from 2.9.1 to 2.9.2, the PDF output by decktape has significantly increased in size.

Compare PDF from #176 : https://github.com/DuaneOBrien/decktape-emoji-bug/blob/master/decktape-emoji-bug-output.pdf : (132k in size)

To PDF generated from the same content post-update: https://github.com/DuaneOBrien/decktape-emoji-bug/blob/master/decktape-emoji-bug-output-post-update.pdf (14.8mb in size)

I have not yet tried trying --screenshots settings to see if this affects the output.

Chrome Version: 72.0.3626.121

**Comment by astefanutti** [comment] 2019-03-14 07:45
I've tried with other presentations and the increase do not happen. So I highly suspect it's caused by the font compression algorithm failing to support Emoji that use zero width joiner sequences.

**Comment by DuaneOBrien** [comment] 2019-03-17 01:16
Bummer!

Is this another bug that's further upstream? Anything I can do to help refine test cases, investigate, etc?

**Comment by astefanutti** [comment] 2019-03-17 15:17
That one is likely on Decktape side. It's likely the way it aggregates font glyphes over slides that doesn't handle emoji correctly:

https://github.com/astefanutti/decktape/blob/46b23e53858c4c29a2027096142effcbc8ea82ee/decktape.js#L407-L452

Your presentation is enough to reproduce and test the future fix.

**Comment by DuaneOBrien** [comment] 2019-10-06 22:18
Hi @astefanutti!

I opened #196 and #197 after I started looking at this bug a little closer. I'd like to see if I can get this one fixed, or at least understand it more, but I wanted to make sure that I understood what testing the fix would look like. Based on what I see in the repository, my plan for testing a fix would be to:

* [ ] verify that the URLs listed in the Examples stanza of the README.md can still be used for testing
* * [ ] Update README.md with any changed/missing URLs
* [ ] re-run decktape against the test URLs
* * [ ] open issues for any plugins that appear to no longer be working
* * [ ] compare the fresh PDFs against the PDFs in docs/samples to confirm they are still accurate
* * [ ] submit a PR to update existing documentation and samples if there are any changes
* [ ] apply possible fixes to #177 to my local branch
* [ ] re-run decktape against the URLs listed in the Examples stanza of the README.md
* * [ ] compare the output PDFs against the newly updated PDFs in docs/samples
* * [ ] verify filesizes are unchanged +/- minor variances
* * [ ] attempt to verify bug fix against https://duaneobrien.github.io/decktape-emoji-bug/#1

Does this look like a sane approach to you? Is there anything else that might be helpful to know before I try fixing the issue?

**Comment by astefanutti** [comment] 2019-10-07 08:31
Hi @DuaneOBrien, this is just perfect! This is pretty much the protocol I use, that is relying on the examples as input for non-regression testing. Granted that, ideally, this should be automated, but this would require a substantial amount of work 😉.

Do not hesitate to report here your progress and questions so that I can help anytime.

**Comment by astefanutti** [comment] 2021-11-30 08:10
I've tested the issue with the latest 3.4.0, and it seem it's fixed. Here is the output PDF: [test.pdf](https://github.com/astefanutti/decktape/files/7623972/test.pdf), which is 290KB in size.

**Comment by astefanutti** [comment] 2022-04-05 20:28
Let me close this as it seems to be fixed in recent versions.

**Closed by astefanutti** 2022-04-05 20:28 UTC
Labels: bug
