### ISSUE TITLE
CSS Media Type

### ISSUE THREAD

**Issue by eljefe6a** [astefanutti/decktape#93] opened 2017-04-21 16:55 UTC
PhantomJS is supposed to set the media type to `print`. Decktape's rendering sets the media type to `screen`. Is there a way to change Decktape's CSS media type to `print`?

I spent a while looking around for the reason for the difference and I couldn't find it.

**Comment by astefanutti** [comment] 2017-04-21 17:09
DeckTape does not use the _standard_ PhantomJS PDF print method. IIRC, this is that method call that set the media type to `print`. As DeckTape uses another _printer_, its leaves the media type to the default `screen`.

It is intended in the sense that most HTML presentations are not meant to be rendered with the `print` media type. For those that does, then I would imagine there is no need for DeckTape and a PDF export / print from the browser should work.

That being said, it would be possible to add an option to set the media type if needed. Would you have more details to share on you use case?

**Comment by eljefe6a** [comment] 2017-04-21 17:18
The use case is that Chrome renders slightly different than PhantomJS. In my case, the font size in PhantomJS's rendered font length is 30 pixels longer than Chrome's. I planned to use `print` to change PhantomJS's font size to be slightly smaller and match Chrome's rendering.

**Comment by eljefe6a** [comment] 2017-04-23 00:27
To make this issue more clear: this extra 30-100 pixels makes my PhantomJS renders have scroll bars on my code snippets. Chrome doesn't have these scroll bars. It completely messes up the slide and I don't have a great to find these scroll bars unless I render out the slides and visually find them.

**Comment by astefanutti** [comment] 2017-04-24 12:02
Would you be able to share a minimal use case / deck that I can use to reproduce the font rendering issue? If yes, I would suggest you create another issue with that specific example. I would rather try to address that root cause rather than trying to support overriding the media type.

**Comment by eljefe6a** [comment] 2017-04-24 12:36
Here's how to repeat:

1. Use Remark
2. Add a fenced code segment that goes all the way to edge of the box in Chrome, but doesn't create a scroll bar. Depending on the font size, that's about 100 characters.
3. Render out the slide with PhantomJS. You will get a scroll bar.

**Comment by astefanutti** [comment] 2017-04-24 12:41
OK I'll try to set that up ASAP. In the meantime, if you have the example code at hand, that'd speed things up 😉.

**Comment by astefanutti** [comment] 2017-08-25 13:31
Should be fixed in version `2.0.1` that uses headless Chrome. We will be able to use the `page.emulateMedia` API if necessary introduces with GoogleChrome/puppeteer#312.

Let me know if you still face this issue.

**Closed by astefanutti** 2017-08-25 13:31 UTC
Labels: question
