### ISSUE TITLE
Error: spawn EACCES on ArchLinux

### ISSUE THREAD

**Issue by adrfantini** [astefanutti/decktape#139] opened 2018-03-26 10:12 UTC
Using `decktape` from the ArchLinux AUR, I get this error when trying to convert anything:

```
Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at Object.exports.spawn (child_process.js:500:9)
    at Function.launch (/usr/lib/node_modules/decktape/node_modules/puppeteer/lib/Launcher.js:100:40)
    at <anonymous>
```

With any command. Also trying some of the example presentations in `https://github.com/astefanutti/decktape`, no difference.

**Comment by pat-s** [comment] 2018-03-26 11:35
At a first glance this seems like an issue of puppeteer: https://github.com/alekzonder/docker-puppeteer/issues/9

I can replicate your issue but its strange as nothing has changed since the creation of the AUR package.

Can you replicate the problem when installing `decktape` using `npm`?

**Comment by adrfantini** [comment] 2018-03-26 16:59
Yep, the problem is there even if using `decktape` from `npm`!

**Comment by astefanutti** [comment] 2018-03-29 10:39
I've been able to reproduce (using the base/archlinux Docker image).

Unfortunately, there is not much that can be done on DeckTape side. This is a Puppeteer install step issue where the Chromium binary (`/usr/lib/node_modules/decktape/node_modules/puppeteer/.local-chromium/`) hasn't the needed permissions.

For some reasons permissions for 
`/usr/lib/node_modules/decktape/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome` is only `-rwx------`. Running:

    $ chmod a+r /usr/lib/node_modules/decktape/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/*
    $ chmod a+x /usr/lib/node_modules/decktape/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome

Fixes things. I would suggest to create an issue in Puppeteer to follow this up.

**Comment by adrfantini** [comment] 2018-03-29 10:47
Done.

**Comment by pat-s** [comment] 2018-03-29 11:16
Thanks guys. I could also manually fix it in the PGKBUILD but let's first see if there is a response from the `puppeteer` guys.

**Comment by astefanutti** [comment] 2018-04-17 07:36
GoogleChrome/puppeteer#2283 has just been fixed. Let me upgrade to Puppeteer `1.3.0` to have this fixed in DeckTape.

**Comment by pat-s** [comment] 2018-04-22 10:14
`decktape` `v2.8.1.` does not yet include the puppeteer fix right? Release notes say that you only upgraded to v1.1.1.

**Comment by astefanutti** [comment] 2018-04-22 11:35
@pat-s right. I'm still holding the Puppeteer upgrade because of GoogleChrome/puppeteer#2411. If you could vote it up, that'd be great.

**Comment by astefanutti** [comment] 2018-05-09 17:56
I've just released version 2.8.3 that contains upstream fix. Let me close this and do not hesitate to re-open if you still face the issue.

**Closed by astefanutti** 2018-05-09 17:56 UTC

**Comment by adrfantini** [comment] 2018-05-09 18:16
Thanks!

**Comment by JJK96** [comment] 2018-06-29 09:06
I have this issue: 
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/decktape/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by JJK96** [comment] 2018-07-01 14:00
The arch linux aur package `nodejs-decktape`, which is version 2.8.0-1.
However, by installing via npm I could get it to work, I did have to add the --no-sandbox flag though.

**Comment by astefanutti** [comment] 2018-07-01 14:02
OK, the `nodejs-decktape` package may not have been updated yet to contain the fix for the `spawn EACCES` error.
